name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Kompajliranje Flutter Aplikacije
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Izgradnja s ažuriranim Kotlinom
        run: |
          flutter create --org hr.broker --project-name bro_ker_ar --platforms android flutter_app
          
          # 1. NOVI STANDARD: Ažuriranje Kotlin verzije direktno u settings.gradle na v1.9.24
          sed -i -E 's/id "org\.jetbrains\.kotlin\.android" version "[^"]*"/id "org.jetbrains.kotlin.android" version "1.9.24"/g' flutter_app/android/settings.gradle
          
          # 2. INJEKCIJE ZA KAMERU:
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' flutter_app/android/app/build.gradle
          sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' flutter_app/android/app/build.gradle
          
          # 3. Prebacivanje koda
          cp -r lib/ flutter_app/
          cp pubspec.yaml flutter_app/
          
          # 4. Kompilacija
          cd flutter_app
          flutter pub get
          flutter build apk --release
          
          # 5. Izvlačenje APK-a
          cp build/app/outputs/flutter-apk/app-release.apk ../

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BRO-KER-AR-App
          path: app-release.apk
          
