name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Kompajliranje Flutter Aplikacije
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Izgradnja s fiksiranim Kotlinom
        run: |
          flutter create --org hr.broker --project-name bro_ker_ar --platforms android flutter_app
          
          # Injekcija za Kotlin verziju u root build.gradle
          sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = '\''1.9.0'\''/g' flutter_app/android/build.gradle
          
          # Injekcije za SDK verzije
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' flutter_app/android/app/build.gradle
          sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' flutter_app/android/app/build.gradle
          
          # Prebacivanje koda
          cp -r lib/ flutter_app/
          cp pubspec.yaml flutter_app/
          
          # Kompilacija
          cd flutter_app
          flutter pub get
          flutter build apk --release
          
          cp build/app/outputs/flutter-apk/app-release.apk ../

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BRO-KER-AR-App
          path: app-release.apk
          
